### ISSUE TITLE
Inconsistency between paper and codes

### ISSUE THREAD

**Issue by SmILeel** [AbnerYang/TII_Wide-Deep_Electricity_Theft_Detection#3]

**Comment by SmILeel** [comment]
![fig](https://user-images.githubusercontent.com/107383023/204956692-23f60d6a-82c2-410e-ad8e-393e476c9d60.jpg)

**Comment by hasanalikhan1266** [comment]
brother do you the dataset and kinldy share with me the dataset of this paper and code Thank you
